
#ifdef REGISTER_MOUSE_AXES
REGISTER_KEYCODE(0, AnyKey)
REGISTER_KEYCODE(0, MouseX)
REGISTER_KEYCODE(0, MouseY)
REGISTER_KEYCODE(0, MouseScrollUp)
REGISTER_KEYCODE(0, MouseScrollDown)
REGISTER_KEYCODE(0, MouseScrollAxis)
#endif

REGISTER_KEYCODE(0, ButtonLeft)
REGISTER_KEYCODE(1, ButtonRight)
REGISTER_KEYCODE(2, ButtonMiddle)
REGISTER_KEYCODE(3, Button3)
REGISTER_KEYCODE(4, Button4)
REGISTER_KEYCODE(5, Button5)
REGISTER_KEYCODE(6, Button6)
REGISTER_KEYCODE(7, Button7)

