-- premake5.lua Game project config

-- GENERATED: VeiM Engine
-- This file is dynamically generated by VeiM Engine during project creation
-- It contains build settings for the game project and configuration details.

-- Include core engine configuration files
include "EngineRoot.lua"								-- Define the root directory of the engine
include (engine_root_dir .. "/Engine/Common.lua")		-- Include shared scripts
include (engine_root_dir .. "/Engine/Dependencies.lua")	-- Include dependencies paths

-- Workspace Definition
workspace "Template_Example"
	architecture "x64"									-- Set the architecture to 64-bit
	startproject "Template_Example"						-- Set the startup module for the workspace
	configurations { "Debug","Debug_Editor", "Development", "Development_Editor", "Shipping" }
	platforms {"Win64"}									-- Target platform
	buildoptions { "/utf-8" }							-- UTF-8 encoding for source files

	-- Additional build options for Visual Studio
	filter "action:vs*"
        buildoptions { "/MP" } -- Enable multi-processor compilation
    filter {}

	filter "configurations:Debug or Development or Shipping"
		defines { "IS_UNIFIED" }
	filter {}
	
	-- Output Directories
	outputdir = "%{cfg.platform}"
	game_bin_out = "%{wks.location}/Binaries/" .. outputdir .. ""
	game_int_out = "%{wks.location}/Intermediate/" .. outputdir .. ""
	engine_bin_out = engine_root_dir .."/Engine/Binaries/Engine/" .. outputdir .. ""
	engine_int_out = engine_root_dir .."/Engine/Intermediate/Engine/" .. outputdir .. ""

-- Include Engine modules to the workspace
group "Engine"
	externalproject "Core"
		location (engine_root_dir .. "/Engine/Build/ProjectFiles")
		language "C++"
		kind "StaticLib" 						-- Default kind 

		filter "configurations:Debug_Editor or Development_Editor" -- Conditional `kind` based on configurations
			kind "SharedLib"  					-- For these configurations, use SharedLib

		filter "configurations:Debug or Development or Shipping"
			kind "StaticLib"  					-- For these configurations, use StaticLib

		filter {}
group ""

group "Engine Dependencies"
	externalproject "GLFW"
		location (engine_root_dir .. "/Engine/ThirdParty/GLFW")
		kind "StaticLib"
		language "C++"
	externalproject "Glad"
		location (engine_root_dir .. "/Engine/ThirdParty/Glad")
		kind "StaticLib"
		language "C++"
	externalproject "ImGui"
		location (engine_root_dir .. "/Engine/ThirdParty/imgui")
		kind "StaticLib"
		language "C++"
	externalproject "yaml-cpp"
		location (engine_root_dir .. "/Engine/ThirdParty/yaml-cpp")
		kind "StaticLib"
		language "C++"
	externalproject "assimp"
		location (engine_root_dir .. "/Engine/ThirdParty/assimp")
		kind "StaticLib"
		language "C++"
	externalproject "CityHash"
		location (engine_root_dir .. "/Engine/ThirdParty/CityHash")
		kind "StaticLib"
		language "C"
group ""

-- Include Game modules to the workspace
group "Game"
	include "Source/Template_Example"
group ""





