-- EngineRoot.lua

-- GENERATED: VeiMManagerTool
-- This file is dynamically generated by VeiM Manager Tool during project files generation with Premake
-- EngineRoot.lua contains the path to the associated engine installation directory.

engine_root_dir = "E:/Dev/Projects/VeiM"