-- premake5.lua Game module config

-- GENERATED: VeiM Engine
-- This file is dynamically generated by VeiM Engine during project creation.
-- It contains build settings for the Game module.


-- Game Module Definition
project "TestVeiMGame"
	-- General Project Settings
    language 		"C++"							-- Specify the programming language
    cppdialect 		"C++20"							-- Use the C++20 standard
    staticruntime 	"off"							-- Disable static runtime linking

	-- Output Directories
    targetdir 		(game_bin_out)					-- Game Binaries output directory
	objdir 			(game_int_out)					-- Game Intermediate files directory
    debugdir 		"%{cfg.targetdir}"				-- Debug directory matches binaries directory

	-- Project Files Location
    location "%{wks.location}/Build/ProjectFiles"

	-- Source Files
    files
    {
        "%{wks.location}/Source/TestVeiMGame/**.h",
        "%{wks.location}/Source/TestVeiMGame/**.cpp"
    }

	-- Include Directories
    includedirs
    {
        "%{wks.location}/Source/TestVeiMGame",		-- Include game source directory
		engine_root_dir .. "/Engine/Source/VeiM",
		engine_root_dir .. "/Engine/ThirdParty/Glad/include",
		engine_root_dir .. "/Engine/ThirdParty/spdlog/include",
		engine_root_dir .. "/Engine/ThirdParty/GLFW/include"

    }

	-- Game Dependencies
    links {"VeiM"}									-- Link against the VeiM Engine

	------------------ Target ----------------------
	local game_standalone_target = dofile("TestVeiMGame.Target.lua")
	local game_editor_target = dofile("TestVeiMGameEditor.Target.lua")

	filter "configurations:Debug"
		local launch_dir = "(ProjectDir)/Binaries/%{cfg.platform}/TestVeiMGame"
		local exe_cfg = "-%{cfg.platform}-Debug"
		local command = "python" .. " "
						.. engine_root_dir .. "/Engine/Programs/vmtarget/vmtarget.py".. " "
						.. "%{cfg.targetdir}/" .. game_standalone_target.name .. exe_cfg ..".target" .. " "
						.. game_standalone_target.name .. " "
						.. "Debug" .. " "
						.. game_standalone_target.type .. " "
						.. "../../TestVeiMGame.vmproject" .. " "
						.. launch_dir .. exe_cfg .. ".exe"
		postbuildcommands{
			command
		}

	filter "configurations:Debug_Editor"
		local launch_dir = "(EngineDir)/Binaries/%{cfg.platform}/%{cfg.buildcfg}/VeiMEditor"
		local exe_cfg = "-%{cfg.platform}-Debug"
		local command = "python" .. " "
						.. engine_root_dir .. "/Engine/Programs/vmtarget/vmtarget.py".. " "
						.. "%{cfg.targetdir}/" .. game_editor_target.name .. exe_cfg ..".target" .. " "
						.. game_editor_target.name .. " "
						.. "Debug" .. " "
						.. game_editor_target.type .. " "
						.. "../../TestVeiMGame.vmproject" .. " "
						.. "\"" .. launch_dir .. exe_cfg .. ".exe\""
		postbuildcommands{
			command
		}

	filter "configurations:Development"
		local launch_dir = "(ProjectDir)/Binaries/%{cfg.platform}/TestVeiMGame"
		local exe_cfg = ""
		local command = "python" .. " "
						.. engine_root_dir .. "/Engine/Programs/vmtarget/vmtarget.py".. " "
						.. "%{cfg.targetdir}/" .. game_standalone_target.name .. exe_cfg ..".target" .. " "
						.. game_standalone_target.name .. " "
						.. "Development" .. " "
						.. game_standalone_target.type .. " "
						.. "../../TestVeiMGame.vmproject" .. " "
						.. launch_dir .. exe_cfg .. ".exe"
		postbuildcommands{
			command
		}
			
	filter "configurations:Development_Editor"
		local launch_dir = "(EngineDir)/Binaries/%{cfg.platform}/%{cfg.buildcfg}/VeiMEditor"
		local exe_cfg = ""
		local command = "python" .. " "
						.. engine_root_dir .. "/Engine/Programs/vmtarget/vmtarget.py".. " "
						.. "%{cfg.targetdir}/" .. game_editor_target.name .. exe_cfg ..".target" .. " "
						.. game_editor_target.name .. " "
						.. "Development" .. " "
						.. game_editor_target.type .. " "
						.. "../../TestVeiMGame.vmproject" .. " "
						.. launch_dir .. exe_cfg .. ".exe"
		postbuildcommands{
			command
		}
	
	filter "configurations:Shipping"
		local launch_dir = "(ProjectDir)/Binaries/%{cfg.platform}/TestVeiMGame"
		local exe_cfg = "-%{cfg.platform}-Shipping"
		local command = "python" .. " "
						.. engine_root_dir .. "/Engine/Programs/vmtarget/vmtarget.py".. " "
						.. "%{cfg.targetdir}/" .. game_standalone_target.name .. exe_cfg ..".target" .. " "
						.. game_standalone_target.name .. " "
						.. "Shipping" .. " "
						.. game_standalone_target.type .. " "
						.. "../../TestVeiMGame.vmproject" .. " "
						.. launch_dir .. exe_cfg .. ".exe"
		postbuildcommands{
			command
		}
	filter {}

	-------------------------------------------------

	-- Debug Configuration
    filter "configurations:Debug"
		kind 	 "ConsoleApp"
		runtime  "Debug"
		symbols  "on"
		defines  "VM_DEBUG"
		targetsuffix "-%{cfg.platform}-Debug"

	-- Debug Editor Configuration
	filter "configurations:Debug_Editor"
		kind 	 "SharedLib"
		runtime  "Debug"
		symbols  "on"
		defines  "VM_DEBUG"
		targetsuffix "-%{cfg.platform}-Debug"
		debugcommand (engine_root_dir .. "/Engine/Binaries/Win64/Debug_Editor/VeiMEditor-Win64-Debug.exe")

	-- Development Configuration
	filter "configurations:Development"
		kind 	 "ConsoleApp"
		runtime  "Release"
		optimize "on"
		symbols  "on"
		defines  "VM_DEVELOPMENT"

	-- Development Editor Configuration
	filter "configurations:Development_Editor"
		kind 	 "SharedLib"
		runtime  "Release"
		optimize "on"
        symbols  "on"
		defines  "VM_DEVELOPMENT"
		debugcommand (engine_root_dir .. "/Engine/Binaries/Win64/Development_Editor/VeiMEditor.exe")

	-- Shipping Configuration
	filter "configurations:Shipping"
		kind 	 "ConsoleApp"
		runtime  "Release"
		optimize "on"
        symbols  "off"
		defines  "VM_SHIPPING"
		targetsuffix "-%{cfg.platform}-Shipping"
	
	-----------------------------------------------------------