-- TestVeiMGame.Target.lua target

-- GENERATED: VeiM Engine
-- This file is dynamically generated by VeiM Engine during project creation.
-- It contains build settings for the Game module.

return {
    name = "TestVeiMGameEditor",
    type = "Editor",
}

