-- Template_Example_target.lua target

-- GENERATED: VeiM Engine
-- This file is dynamically generated by VeiM Engine during project creation.
-- It contains target settings for the Game module.

return {
    name = "Template_Example",
    type = "Game",
}

